version: 1.0.'{build}'

image:
 - Visual Studio 2017

configuration: Release

platform: x64
stack: jdk 11

build_script:
  - cmd: vcpkg.exe install pthreads:x64-windows
  - cmd: cd java && build.bat
  - cmd: cd java && mvn -DskipTests -q package

artifacts:
  - path: java/build/Release/webrtc-vad-java.dll
    name: webrtc-vad-java.dll
  - path: java/build/Release/pthreadVC3.dll
    name: pthreadVC3.dll
  - path: java/target/webrtc-vad-java-1.0.0.jar
    name: webrtc-vad-java